// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeachingBACKEND.Data;

#nullable disable

namespace TeachingBACKEND.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250512134522_SeedAlbanianCities")]
    partial class SeedAlbanianCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2d4a4ee-5fa2-4a33-bd3c-2bbf98e9310b"),
                            Name = "Tirana"
                        },
                        new
                        {
                            Id = new Guid("b8e13e5a-bba4-48b6-99d6-c4f123ab2cb3"),
                            Name = "Durrës"
                        },
                        new
                        {
                            Id = new Guid("d05f0e99-20f0-4c9a-b03f-3ea92ec02b41"),
                            Name = "Shkodër"
                        },
                        new
                        {
                            Id = new Guid("bc4e14b5-7d7e-4b6c-8b33-eaa2c91f9015"),
                            Name = "Vlorë"
                        },
                        new
                        {
                            Id = new Guid("2dff0b99-3d86-47a5-b7ad-4e6d3c0ec748"),
                            Name = "Elbasan"
                        },
                        new
                        {
                            Id = new Guid("12f4c32b-4a42-4b1f-9247-9b40efb21363"),
                            Name = "Fier"
                        },
                        new
                        {
                            Id = new Guid("f8d8e184-74c0-4551-b66b-7ae3f05e7ff5"),
                            Name = "Korçë"
                        },
                        new
                        {
                            Id = new Guid("69e02c84-4a61-406e-844d-24df2e25a983"),
                            Name = "Gjirokastër"
                        },
                        new
                        {
                            Id = new Guid("8e065f0d-71c1-4a63-804b-49b1d08c1407"),
                            Name = "Berat"
                        },
                        new
                        {
                            Id = new Guid("d28f0be5-5f17-4ec8-b365-7387c22234e9"),
                            Name = "Lezhë"
                        },
                        new
                        {
                            Id = new Guid("e5f957d6-7a31-45b2-bded-44e4992d4b83"),
                            Name = "Kukës"
                        });
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("EmailVerificationToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PasswordResetToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ApprovalStatus = 1,
                            City = "Tirana",
                            DateOfBirth = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@teachapp.com",
                            FirstName = "System",
                            IsEmailVerified = true,
                            LastName = "Administrator",
                            PasswordHash = "$2a$12$6SPhwV64Lpb1/OdZIkXAH.r5/fXJJUgQsVBCCycmRW/.F5N6wA7M2",
                            PhoneNumber = "+35500000000",
                            Profession = "Administrator",
                            RefreshToken = new Guid("00000000-0000-0000-0000-000000000000"),
                            RefreshTokenExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0,
                            School = "Main Admin Office"
                        });
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Payment", b =>
                {
                    b.HasOne("TeachingBACKEND.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.User", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
