// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeachingBACKEND.Data;

#nullable disable

namespace TeachingBACKEND.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250821171827_AddQuizTypes")]
    partial class AddQuizTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2d4a4ee-5fa2-4a33-bd3c-2bbf98e9310b"),
                            Name = "Tirana"
                        },
                        new
                        {
                            Id = new Guid("b8e13e5a-bba4-48b6-99d6-c4f123ab2cb3"),
                            Name = "Durrës"
                        },
                        new
                        {
                            Id = new Guid("d05f0e99-20f0-4c9a-b03f-3ea92ec02b41"),
                            Name = "Shkodër"
                        },
                        new
                        {
                            Id = new Guid("bc4e14b5-7d7e-4b6c-8b33-eaa2c91f9015"),
                            Name = "Vlorë"
                        },
                        new
                        {
                            Id = new Guid("2dff0b99-3d86-47a5-b7ad-4e6d3c0ec748"),
                            Name = "Elbasan"
                        },
                        new
                        {
                            Id = new Guid("12f4c32b-4a42-4b1f-9247-9b40efb21363"),
                            Name = "Fier"
                        },
                        new
                        {
                            Id = new Guid("f8d8e184-74c0-4551-b66b-7ae3f05e7ff5"),
                            Name = "Korçë"
                        },
                        new
                        {
                            Id = new Guid("69e02c84-4a61-406e-844d-24df2e25a983"),
                            Name = "Gjirokastër"
                        },
                        new
                        {
                            Id = new Guid("8e065f0d-71c1-4a63-804b-49b1d08c1407"),
                            Name = "Berat"
                        },
                        new
                        {
                            Id = new Guid("d28f0be5-5f17-4ec8-b365-7387c22234e9"),
                            Name = "Lezhë"
                        },
                        new
                        {
                            Id = new Guid("e5f957d6-7a31-45b2-bded-44e4992d4b83"),
                            Name = "Kukës"
                        });
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3f9a8f1-9c4e-4a91-8bcb-0b6b1583d3a1"),
                            Name = "Klasa 1"
                        },
                        new
                        {
                            Id = new Guid("a61d58b7-23f8-48f7-9778-3e048c5808a0"),
                            Name = "Klasa 2"
                        },
                        new
                        {
                            Id = new Guid("81bce1db-4f7c-4f6f-9e59-cde56a8200b6"),
                            Name = "Klasa 3"
                        },
                        new
                        {
                            Id = new Guid("f82a2ea4-c4c9-4895-9484-0197a299c02f"),
                            Name = "Klasa 4"
                        },
                        new
                        {
                            Id = new Guid("10840373-f0f4-4b10-9ee0-c5a831b6cf6a"),
                            Name = "Klasa 5"
                        },
                        new
                        {
                            Id = new Guid("7fc8018d-6310-4c1f-b878-4b3a5b0b265c"),
                            Name = "Klasa 6"
                        },
                        new
                        {
                            Id = new Guid("8e77a87f-e42b-487a-9cde-54f648c8c457"),
                            Name = "Klasa 7"
                        },
                        new
                        {
                            Id = new Guid("43e7b804-0e1a-4c82-9e44-6a194ee1ff63"),
                            Name = "Klasa 8"
                        },
                        new
                        {
                            Id = new Guid("fd4b14ea-1b79-4e4c-83e0-0196c55b4bc1"),
                            Name = "Klasa 9"
                        },
                        new
                        {
                            Id = new Guid("1c0b8bb7-9eb9-4a4d-8c4d-67de8057ae49"),
                            Name = "Klasa 10"
                        },
                        new
                        {
                            Id = new Guid("3402fc90-d7be-420e-a980-2ff430d84838"),
                            Name = "Klasa 11"
                        },
                        new
                        {
                            Id = new Guid("013d0df5-50ef-4269-8a12-9b4f91ef07e1"),
                            Name = "Klasa 12"
                        });
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.LearnHub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LearnHubs");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("LearnHubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LearnHubId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuizzId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizzId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.QuizType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuizTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b1b1b1-b1b1-1111-1111-111111111111"),
                            Name = "text"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-b2b2-2222-2222-222222222222"),
                            Name = "imazhe"
                        });
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Quizz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("bit");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.RegistrationPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFamilyPlan")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("RegistrationPlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistrationPlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-1111-1111-111111111111"),
                            IsFamilyPlan = false,
                            MaxUsers = 1,
                            Price = 2000L,
                            RegistrationPlanName = "Bazë",
                            StripeProductName = "Student - Monthly Bazë",
                            Type = "monthly",
                            UserType = "student"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-2222-2222-222222222222"),
                            IsFamilyPlan = false,
                            MaxUsers = 1,
                            Price = 4000L,
                            RegistrationPlanName = "Standarde",
                            StripeProductName = "Student - Monthly Standarde",
                            Type = "monthly",
                            UserType = "student"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-3333-3333-333333333333"),
                            IsFamilyPlan = false,
                            MaxUsers = 1,
                            Price = 6000L,
                            RegistrationPlanName = "Premium",
                            StripeProductName = "Student - Monthly Premium",
                            Type = "monthly",
                            UserType = "student"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-4444-4444-444444444444"),
                            IsFamilyPlan = false,
                            MaxUsers = 1,
                            Price = 20000L,
                            RegistrationPlanName = "Bazë",
                            StripeProductName = "Student - Yearly Bazë",
                            Type = "yearly",
                            UserType = "student"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-5555-5555-555555555555"),
                            IsFamilyPlan = true,
                            MaxUsers = 5,
                            Price = 40000L,
                            RegistrationPlanName = "Standarde",
                            StripeProductName = "Student - Yearly Standarde",
                            Type = "yearly",
                            UserType = "family"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-6666-6666-666666666666"),
                            IsFamilyPlan = true,
                            MaxUsers = 10,
                            Price = 60000L,
                            RegistrationPlanName = "Premium",
                            StripeProductName = "Student - Yearly Premium",
                            Type = "yearly",
                            UserType = "family"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-7777-7777-777777777777"),
                            IsFamilyPlan = false,
                            MaxUsers = 50,
                            Price = 10000L,
                            RegistrationPlanName = "Supervisor - Monthly",
                            StripeProductName = "Supervisor - Monthly Plan",
                            Type = "monthly",
                            UserType = "supervisor"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-8888-8888-888888888888"),
                            IsFamilyPlan = false,
                            MaxUsers = 500,
                            Price = 100000L,
                            RegistrationPlanName = "Supervisor - Yearly",
                            StripeProductName = "Supervisor - Yearly Plan",
                            Type = "yearly",
                            UserType = "supervisor"
                        });
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Subjects", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dbe6757d-2138-463a-bee7-5d07a6d7b320"),
                            Name = "Letërsi"
                        },
                        new
                        {
                            Id = new Guid("616273bd-2a2a-4894-b689-57fe86702ae0"),
                            Name = "Matematik"
                        },
                        new
                        {
                            Id = new Guid("a072e5ed-714d-40d3-9af8-3b5b940acd2f"),
                            Name = "Anglisht"
                        },
                        new
                        {
                            Id = new Guid("a5cf5e27-ef08-4fef-b907-109496b284eb"),
                            Name = "Histori"
                        },
                        new
                        {
                            Id = new Guid("5eac82ae-0b4b-47a8-9871-ba6ab1c99df7"),
                            Name = "Gjeografi"
                        },
                        new
                        {
                            Id = new Guid("faf6b93a-91d1-4ead-85f5-0120ac85f7d2"),
                            Name = "Shkenca"
                        });
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("EmailVerificationToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PasswordResetToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ApprovalStatus = 1,
                            City = "Tirana",
                            CreateAt = new DateTime(2025, 8, 21, 17, 18, 27, 9, DateTimeKind.Utc).AddTicks(9850),
                            DateOfBirth = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@teachapp.com",
                            FirstName = "System",
                            IsEmailVerified = true,
                            LastName = "Administrator",
                            PasswordHash = "$2a$12$Iisuhi873n9k09G6TGeHx.yuj8acLNdp7dudoDV4bT5Ag0cmmeBbW",
                            PhoneNumber = "+35500000000",
                            Profession = "Administrator",
                            RefreshToken = new Guid("00000000-0000-0000-0000-000000000000"),
                            RefreshTokenExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0,
                            School = "Main Admin Office"
                        });
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Link", b =>
                {
                    b.HasOne("TeachingBACKEND.Domain.Entities.LearnHub", "LearnHub")
                        .WithMany("Links")
                        .HasForeignKey("LearnHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnHub");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Option", b =>
                {
                    b.HasOne("TeachingBACKEND.Domain.Entities.Quizz", "Quizz")
                        .WithMany("Options")
                        .HasForeignKey("QuizzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quizz");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Payment", b =>
                {
                    b.HasOne("TeachingBACKEND.Domain.Entities.RegistrationPlan", "Plan")
                        .WithMany("Payments")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TeachingBACKEND.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Quizz", b =>
                {
                    b.HasOne("TeachingBACKEND.Domain.Entities.Link", "Link")
                        .WithMany("Quizzes")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.LearnHub", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Link", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.Quizz", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.RegistrationPlan", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TeachingBACKEND.Domain.Entities.User", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
